<div id="cityarea" class="pop search-citys-pop click new_showadress">
    <a href="javascript:void(0)" class="pop-close">X</a>
    <div class="search-citys-tit click">热门城市(可直接输入中文名/拼音/三字码)</div>
    <div class="search-citys-tt click">
        <a class="current click" href="javascript:void(0)">热门<span></span></a>
        <a class="click" href="javascript:void(0)">ABCDEFG<span></span></a>
        <a class="click" href="javascript:void(0)">HIJKL<span></span></a>
        <a class="click" href="javascript:void(0)">MNOPQRST<span></span></a>
        <a class="click" href="javascript:void(0)">UVWXYZ<span></span></a>
    </div>
    <div class="search-citys-list click">
        <ul>
            <li class="click"><a href="javascript:;">北京</a></li>
            <li class="click"><a href="javascript:;">上海</a></li>
            <li class="click"><a href="javascript:;">广州</a></li>
            <li class="click"><a href="javascript:;">深圳</a></li>
            <li class="click"><a href="javascript:;">天津</a></li>
            <li class="click"><a href="javascript:;">重庆</a></li>
            <li class="click"><a href="javascript:;">南京</a></li>
            <li class="click"><a href="javascript:;">武汉</a></li>
            <li class="click"><a href="javascript:;">西安</a></li>
            <li class="click"><a href="javascript:;">杭州</a></li>
            <li class="click"><a href="javascript:;">成都</a></li>
            <li class="click"><a href="javascript:;">济南</a></li>
            <li class="click"><a href="javascript:;">苏州</a></li>
            <li class="click"><a href="javascript:;">东莞</a></li>
            <li class="click"><a href="javascript:;">郑州</a></li>
            <li class="click"><a href="javascript:;">宁波</a></li>
        </ul>
        <ul style="display: none;">
            <li class="click"><a href="javascript:;">鞍山</a></li>
            <li class="click"><a href="javascript:;">安阳</a></li>
            <li class="click"><a href="javascript:;">安庆</a></li>
            <li class="click"><a href="javascript:;">阿克苏</a></li>
            <li class="click"><a href="javascript:;">安顺</a></li>
            <li class="click"><a href="javascript:;">安康</a></li>
            <li class="click"><a href="javascript:;">北京</a></li>
            <li class="click"><a href="javascript:;">包头</a></li>
            <li class="click"><a href="javascript:;">蚌埠</a></li>
            <li class="click"><a href="javascript:;">保定</a></li>
            <li class="click"><a href="javascript:;">北海</a></li>
            <li class="click"><a href="javascript:;">保亭</a></li>
            <li class="click"><a href="javascript:;">宝鸡</a></li>
            <li class="click"><a href="javascript:;">本溪</a></li>
            <li class="click"><a href="javascript:;">白山</a></li>
            <li class="click"><a href="javascript:;">白城</a></li>
            <li class="click"><a href="javascript:;">亳州</a></li>
            <li class="click"><a href="javascript:;">巴中</a></li>
            <li class="click"><a href="javascript:;">白银</a></li>
            <li class="click"><a href="javascript:;">滨州</a></li>
            <li class="click"><a href="javascript:;">保山</a></li>
            <li class="click"><a href="javascript:;">毕节</a></li>
            <li class="click"><a href="javascript:;">宝安</a></li>
            <li class="click"><a href="javascript:;">博罗</a></li>
            <li class="click"><a href="javascript:;">重庆</a></li>
            <li class="click"><a href="javascript:;">长沙</a></li>
            <li class="click"><a href="javascript:;">成都</a></li>
            <li class="click"><a href="javascript:;">长春</a></li>
            <li class="click"><a href="javascript:;">常德</a></li>
            <li class="click"><a href="javascript:;">承德</a></li>
            <li class="click"><a href="javascript:;">常州</a></li>
            <li class="click"><a href="javascript:;">常熟</a></li>
            <li class="click"><a href="javascript:;">池州</a></li>
            <li class="click"><a href="javascript:;">巢湖</a></li>
            <li class="click"><a href="javascript:;">从化</a></li>
            <li class="click"><a href="javascript:;">长乐</a></li>
            <li class="click"><a href="javascript:;">昌吉</a></li>
            <li class="click"><a href="javascript:;">郴州</a></li>
            <li class="click"><a href="javascript:;">长治</a></li>
            <li class="click"><a href="javascript:;">赤峰</a></li>
            <li class="click"><a href="javascript:;">赤水</a></li>
            <li class="click"><a href="javascript:;">潮州</a></li>
            <li class="click"><a href="javascript:;">沧州</a></li>
            <li class="click"><a href="javascript:;">滁州</a></li>
            <li class="click"><a href="javascript:;">朝阳</a></li>
            <li class="click"><a href="javascript:;">淳安</a></li>
            <li class="click"><a href="javascript:;">长沙县</a></li>
            <li class="click"><a href="javascript:;">楚雄</a></li>
            <li class="click"><a href="javascript:;">慈溪</a></li>
            <li class="click"><a href="javascript:;">长安</a></li>
            <li class="click"><a href="javascript:;">常平</a></li>
            <li class="click"><a href="javascript:;">樟木头</a></li>
            <li class="click"><a href="javascript:;">大同</a></li>
            <li class="click"><a href="javascript:;">东营</a></li>
            <li class="click"><a href="javascript:;">大连</a></li>
            <li class="click"><a href="javascript:;">大庆</a></li>
            <li class="click"><a href="javascript:;">东莞</a></li>
            <li class="click"><a href="javascript:;">东阳</a></li>
            <li class="click"><a href="javascript:;">丹东</a></li>
            <li class="click"><a href="javascript:;">丹阳</a></li>
            <li class="click"><a href="javascript:;">德州</a></li>
            <li class="click"><a href="javascript:;">德阳</a></li>
            <li class="click"><a href="javascript:;">大理</a></li>
            <li class="click"><a href="javascript:;">敦化</a></li>
            <li class="click"><a href="javascript:;">德惠</a></li>
            <li class="click"><a href="javascript:;">登封</a></li>
            <li class="click"><a href="javascript:;">定州</a></li>
            <li class="click"><a href="javascript:;">都匀</a></li>
            <li class="click"><a href="javascript:;">敦煌</a></li>
            <li class="click"><a href="javascript:;">东港</a></li>
            <li class="click"><a href="javascript:;">大石桥</a></li>
            <li class="click"><a href="javascript:;">灯塔</a></li>
            <li class="click"><a href="javascript:;">大兴安岭</a></li>
            <li class="click"><a href="javascript:;">大安</a></li>
            <li class="click"><a href="javascript:;">达州</a></li>
            <li class="click"><a href="javascript:;">都江堰</a></li>
            <li class="click"><a href="javascript:;">定西</a></li>
            <li class="click"><a href="javascript:;">东台</a></li>
            <li class="click"><a href="javascript:;">大丰</a></li>
            <li class="click"><a href="javascript:;">邓州</a></li>
            <li class="click"><a href="javascript:;">大朗</a></li>
            <li class="click"><a href="javascript:;">大岭山</a></li>
            <li class="click"><a href="javascript:;">鄂尔多斯</a></li>
            <li class="click"><a href="javascript:;">鄂州</a></li>
            <li class="click"><a href="javascript:;">峨眉山</a></li>
            <li class="click"><a href="javascript:;">恩施</a></li>
            <li class="click"><a href="javascript:;">二连浩特</a></li>
            <li class="click"><a href="javascript:;">恩平</a></li>
            <li class="click"><a href="javascript:;">福州</a></li>
            <li class="click"><a href="javascript:;">佛山</a></li>
            <li class="click"><a href="javascript:;">阜阳</a></li>
            <li class="click"><a href="javascript:;">富阳</a></li>
            <li class="click"><a href="javascript:;">抚州</a></li>
            <li class="click"><a href="javascript:;">肥东县</a></li>
            <li class="click"><a href="javascript:;">肥西县</a></li>
            <li class="click"><a href="javascript:;">抚顺</a></li>
            <li class="click"><a href="javascript:;">阜新</a></li>
            <li class="click"><a href="javascript:;">凤城</a></li>
            <li class="click"><a href="javascript:;">丰城</a></li>
            <li class="click"><a href="javascript:;">福泉</a></li>
            <li class="click"><a href="javascript:;">防城港</a></li>
            <li class="click"><a href="javascript:;">奉化</a></li>
            <li class="click"><a href="javascript:;">凤岗</a></li>
            <li class="click"><a href="javascript:;">广州</a></li>
            <li class="click"><a href="javascript:;">贵阳</a></li>
            <li class="click"><a href="javascript:;">桂林</a></li>
            <li class="click"><a href="javascript:;">赣州</a></li>
            <li class="click"><a href="javascript:;">盖州</a></li>
            <li class="click"><a href="javascript:;">公主岭</a></li>
            <li class="click"><a href="javascript:;">藁城</a></li>
            <li class="click"><a href="javascript:;">甘南</a></li>
            <li class="click"><a href="javascript:;">高安</a></li>
            <li class="click"><a href="javascript:;">固原</a></li>
            <li class="click"><a href="javascript:;">个旧</a></li>
            <li class="click"><a href="javascript:;">贵港</a></li>
            <li class="click"><a href="javascript:;">巩义</a></li>
            <li class="click"><a href="javascript:;">高明</a></li>
        </ul>
        <ul style="display: none">
            <li class="click"><a href="javascript:;">杭州</a></li>
            <li class="click"><a href="javascript:;">哈尔滨</a></li>
            <li class="click"><a href="javascript:;">海口</a></li>
            <li class="click"><a href="javascript:;">合肥</a></li>
            <li class="click"><a href="javascript:;">呼和浩特</a></li>
            <li class="click"><a href="javascript:;">葫芦岛</a></li>
            <li class="click"><a href="javascript:;">淮安</a></li>
            <li class="click"><a href="javascript:;">惠州</a></li>
            <li class="click"><a href="javascript:;">湖州</a></li>
            <li class="click"><a href="javascript:;">衡阳</a></li>
            <li class="click"><a href="javascript:;">海宁</a></li>
            <li class="click"><a href="javascript:;">汉中</a></li>
            <li class="click"><a href="javascript:;">黄石</a></li>
            <li class="click"><a href="javascript:;">邯郸</a></li>
            <li class="click"><a href="javascript:;">河源</a></li>
            <li class="click"><a href="javascript:;">黄山</a></li>
            <li class="click"><a href="javascript:;">淮北</a></li>
            <li class="click"><a href="javascript:;">淮南</a></li>
            <li class="click"><a href="javascript:;">花都</a></li>
            <li class="click"><a href="javascript:;">鹤壁</a></li>
            <li class="click"><a href="javascript:;">惠东</a></li>
            <li class="click"><a href="javascript:;">怀化</a></li>
            <li class="click"><a href="javascript:;">和田</a></li>
            <li class="click"><a href="javascript:;">哈密</a></li>
            <li class="click"><a href="javascript:;">海城</a></li>
            <li class="click"><a href="javascript:;">衡水</a></li>
            <li class="click"><a href="javascript:;">菏泽</a></li>
            <li class="click"><a href="javascript:;">黑河</a></li>
            <li class="click"><a href="javascript:;">鹤岗</a></li>
            <li class="click"><a href="javascript:;">桦甸</a></li>
            <li class="click"><a href="javascript:;">珲春</a></li>
            <li class="click"><a href="javascript:;">和龙</a></li>
            <li class="click"><a href="javascript:;">华阴</a></li>
            <li class="click"><a href="javascript:;">韩城</a></li>
            <li class="click"><a href="javascript:;">河间</a></li>
            <li class="click"><a href="javascript:;">黄冈</a></li>
            <li class="click"><a href="javascript:;">海拉尔</a></li>
            <li class="click"><a href="javascript:;">河池</a></li>
            <li class="click"><a href="javascript:;">虎门</a></li>
            <li class="click"><a href="javascript:;">厚街</a></li>
            <li class="click"><a href="javascript:;">济南</a></li>
            <li class="click"><a href="javascript:;">金华</a></li>
            <li class="click"><a href="javascript:;">嘉兴</a></li>
            <li class="click"><a href="javascript:;">济宁</a></li>
            <li class="click"><a href="javascript:;">锦州</a></li>
            <li class="click"><a href="javascript:;">吉林</a></li>
            <li class="click"><a href="javascript:;">江门</a></li>
            <li class="click"><a href="javascript:;">晋城</a></li>
            <li class="click"><a href="javascript:;">晋中</a></li>
            <li class="click"><a href="javascript:;">吉安</a></li>
            <li class="click"><a href="javascript:;">景德镇</a></li>
            <li class="click"><a href="javascript:;">九江</a></li>
            <li class="click"><a href="javascript:;">荆州</a></li>
            <li class="click"><a href="javascript:;">焦作</a></li>
            <li class="click"><a href="javascript:;">江阴</a></li>
            <li class="click"><a href="javascript:;">晋江</a></li>
            <li class="click"><a href="javascript:;">建德</a></li>
            <li class="click"><a href="javascript:;">集安</a></li>
            <li class="click"><a href="javascript:;">蛟河</a></li>
            <li class="click"><a href="javascript:;">荆门</a></li>
            <li class="click"><a href="javascript:;">佳木斯</a></li>
            <li class="click"><a href="javascript:;">揭阳</a></li>
            <li class="click"><a href="javascript:;">鸡西</a></li>
            <li class="click"><a href="javascript:;">靖江</a></li>
            <li class="click"><a href="javascript:;">济源</a></li>
            <li class="click"><a href="javascript:;">九台</a></li>
            <li class="click"><a href="javascript:;">晋州</a></li>
            <li class="click"><a href="javascript:;">冀州</a></li>
            <li class="click"><a href="javascript:;">嘉峪关</a></li>
            <li class="click"><a href="javascript:;">酒泉</a></li>
            <li class="click"><a href="javascript:;">金昌</a></li>
            <li class="click"><a href="javascript:;">井冈山</a></li>
            <li class="click"><a href="javascript:;">界首</a></li>
            <li class="click"><a href="javascript:;">江都</a></li>
            <li class="click"><a href="javascript:;">姜堰</a></li>
            <li class="click"><a href="javascript:;">句容</a></li>
            <li class="click"><a href="javascript:;">建湖县</a></li>
            <li class="click"><a href="javascript:;">胶南</a></li>
            <li class="click"><a href="javascript:;">即墨</a></li>
            <li class="click"><a href="javascript:;">景洪</a></li>
            <li class="click"><a href="javascript:;">江山</a></li>
            <li class="click"><a href="javascript:;">昆明</a></li>
            <li class="click"><a href="javascript:;">克拉玛依</a></li>
            <li class="click"><a href="javascript:;">昆山</a></li>
            <li class="click"><a href="javascript:;">库尔勒</a></li>
            <li class="click"><a href="javascript:;">奎屯</a></li>
            <li class="click"><a href="javascript:;">开封</a></li>
            <li class="click"><a href="javascript:;">喀什</a></li>
            <li class="click"><a href="javascript:;">凯里</a></li>
            <li class="click"><a href="javascript:;">开平</a></li>
            <li class="click"><a href="javascript:;">兰州</a></li>
            <li class="click"><a href="javascript:;">临汾</a></li>
            <li class="click"><a href="javascript:;">临沂</a></li>
            <li class="click"><a href="javascript:;">莱芜</a></li>
            <li class="click"><a href="javascript:;">连云港</a></li>
            <li class="click"><a href="javascript:;">洛阳</a></li>
            <li class="click"><a href="javascript:;">廊坊</a></li>
            <li class="click"><a href="javascript:;">柳州</a></li>
            <li class="click"><a href="javascript:;">龙岩</a></li>
            <li class="click"><a href="javascript:;">泸州</a></li>
            <li class="click"><a href="javascript:;">六安</a></li>
            <li class="click"><a href="javascript:;">聊城</a></li>
            <li class="click"><a href="javascript:;">拉萨</a></li>
            <li class="click"><a href="javascript:;">浏阳</a></li>
            <li class="click"><a href="javascript:;">丽江</a></li>
            <li class="click"><a href="javascript:;">乐山</a></li>
            <li class="click"><a href="javascript:;">吕梁</a></li>
            <li class="click"><a href="javascript:;">乐陵</a></li>
            <li class="click"><a href="javascript:;">辽阳</a></li>
            <li class="click"><a href="javascript:;">辽源</a></li>
            <li class="click"><a href="javascript:;">临江</a></li>
            <li class="click"><a href="javascript:;">六盘水</a></li>
            <li class="click"><a href="javascript:;">漯河</a></li>
            <li class="click"><a href="javascript:;">龙井</a></li>
            <li class="click"><a href="javascript:;">鹿泉</a></li>
            <li class="click"><a href="javascript:;">陇南</a></li>
            <li class="click"><a href="javascript:;">临夏</a></li>
            <li class="click"><a href="javascript:;">乐平</a></li>
            <li class="click"><a href="javascript:;">醴陵</a></li>
            <li class="click"><a href="javascript:;">耒阳</a></li>
            <li class="click"><a href="javascript:;">冷水江</a></li>
            <li class="click"><a href="javascript:;">龙口</a></li>
            <li class="click"><a href="javascript:;">莱阳</a></li>
            <li class="click"><a href="javascript:;">临沧</a></li>
            <li class="click"><a href="javascript:;">灵宝</a></li>
            <li class="click"><a href="javascript:;">龙华</a></li>
            <li class="click"><a href="javascript:;">龙门</a></li>
            <li class="click"><a href="javascript:;">临安</a></li>
            <li class="click"><a href="javascript:;">丽水</a></li>
            <li class="click"><a href="javascript:;">临海</a></li>
            <li class="click"><a href="javascript:;">乐清</a></li>
            <li class="click"><a href="javascript:;">兰溪</a></li>
            <li class="click"><a href="javascript:;">龙泉</a></li>
            <li class="click"><a href="javascript:;">龙岗</a></li>
            <li class="click"><a href="javascript:;">来宾区</a></li>
        </ul>
        <ul style="display: none">
            <li class="click"><a href="javascript:;">马鞍山</a></li>
            <li class="click"><a href="javascript:;">绵阳</a></li>
            <li class="click"><a href="javascript:;">牡丹江</a></li>
            <li class="click"><a href="javascript:;">茂名</a></li>
            <li class="click"><a href="javascript:;">梅河口</a></li>
            <li class="click"><a href="javascript:;">梅州</a></li>
            <li class="click"><a href="javascript:;">眉山</a></li>
            <li class="click"><a href="javascript:;">明光</a></li>
            <li class="click"><a href="javascript:;">蒙自</a></li>
            <li class="click"><a href="javascript:;">孟州</a></li>
            <li class="click"><a href="javascript:;">南昌</a></li>
            <li class="click"><a href="javascript:;">南京</a></li>
            <li class="click"><a href="javascript:;">南宁</a></li>
            <li class="click"><a href="javascript:;">宁波</a></li>
            <li class="click"><a href="javascript:;">南通</a></li>
            <li class="click"><a href="javascript:;">宁德</a></li>
            <li class="click"><a href="javascript:;">南平</a></li>
            <li class="click"><a href="javascript:;">南安</a></li>
            <li class="click"><a href="javascript:;">南充</a></li>
            <li class="click"><a href="javascript:;">南阳</a></li>
            <li class="click"><a href="javascript:;">内江</a></li>
            <li class="click"><a href="javascript:;">南宫</a></li>
            <li class="click"><a href="javascript:;">南康</a></li>
            <li class="click"><a href="javascript:;">宁国</a></li>
            <li class="click"><a href="javascript:;">南海</a></li>
            <li class="click"><a href="javascript:;">盘锦</a></li>
            <li class="click"><a href="javascript:;">濮阳</a></li>
            <li class="click"><a href="javascript:;">番禺</a></li>
            <li class="click"><a href="javascript:;">萍乡</a></li>
            <li class="click"><a href="javascript:;">攀枝花</a></li>
            <li class="click"><a href="javascript:;">普洱</a></li>
            <li class="click"><a href="javascript:;">平顶山</a></li>
            <li class="click"><a href="javascript:;">普兰店</a></li>
            <li class="click"><a href="javascript:;">磐石</a></li>
            <li class="click"><a href="javascript:;">莆田</a></li>
            <li class="click"><a href="javascript:;">平凉</a></li>
            <li class="click"><a href="javascript:;">鄱阳</a></li>
            <li class="click"><a href="javascript:;">邳州</a></li>
            <li class="click"><a href="javascript:;">沛县</a></li>
            <li class="click"><a href="javascript:;">平度</a></li>
            <li class="click"><a href="javascript:;">蓬莱</a></li>
            <li class="click"><a href="javascript:;">青岛</a></li>
            <li class="click"><a href="javascript:;">齐齐哈尔</a></li>
            <li class="click"><a href="javascript:;">秦皇岛</a></li>
            <li class="click"><a href="javascript:;">泉州</a></li>
            <li class="click"><a href="javascript:;">迁安</a></li>
            <li class="click"><a href="javascript:;">清远</a></li>
            <li class="click"><a href="javascript:;">衢州</a></li>
            <li class="click"><a href="javascript:;">曲靖</a></li>
            <li class="click"><a href="javascript:;">曲阜</a></li>
            <li class="click"><a href="javascript:;">七台河</a></li>
            <li class="click"><a href="javascript:;">庆阳</a></li>
            <li class="click"><a href="javascript:;">潜江</a></li>
            <li class="click"><a href="javascript:;">青州</a></li>
            <li class="click"><a href="javascript:;">青铜峡</a></li>
            <li class="click"><a href="javascript:;">钦州</a></li>
            <li class="click"><a href="javascript:;">沁阳</a></li>
            <li class="click"><a href="javascript:;">日照</a></li>
            <li class="click"><a href="javascript:;">瑞丽</a></li>
            <li class="click"><a href="javascript:;">汝州</a></li>
            <li class="click"><a href="javascript:;">仁怀</a></li>
            <li class="click"><a href="javascript:;">任丘</a></li>
            <li class="click"><a href="javascript:;">瑞金</a></li>
            <li class="click"><a href="javascript:;">荣成</a></li>
            <li class="click"><a href="javascript:;">瑞安</a></li>
            <li class="click"><a href="javascript:;">上海</a></li>
            <li class="click"><a href="javascript:;">深圳</a></li>
            <li class="click"><a href="javascript:;">沈阳</a></li>
            <li class="click"><a href="javascript:;">绍兴</a></li>
            <li class="click"><a href="javascript:;">苏州</a></li>
            <li class="click"><a href="javascript:;">三亚</a></li>
            <li class="click"><a href="javascript:;">石家庄</a></li>
            <li class="click"><a href="javascript:;">上饶</a></li>
            <li class="click"><a href="javascript:;">汕头</a></li>
            <li class="click"><a href="javascript:;">韶关</a></li>
            <li class="click"><a href="javascript:;">宿迁</a></li>
            <li class="click"><a href="javascript:;">顺德</a></li>
            <li class="click"><a href="javascript:;">双鸭山</a></li>
            <li class="click"><a href="javascript:;">绥化</a></li>
            <li class="click"><a href="javascript:;">石狮</a></li>
            <li class="click"><a href="javascript:;">三明</a></li>
            <li class="click"><a href="javascript:;">随州</a></li>
            <li class="click"><a href="javascript:;">石河子</a></li>
            <li class="click"><a href="javascript:;">邵阳</a></li>
            <li class="click"><a href="javascript:;">韶山</a></li>
            <li class="click"><a href="javascript:;">朔州</a></li>
            <li class="click"><a href="javascript:;">寿光</a></li>
            <li class="click"><a href="javascript:;">十堰</a></li>
            <li class="click"><a href="javascript:;">商丘</a></li>
            <li class="click"><a href="javascript:;">绥芬河</a></li>
            <li class="click"><a href="javascript:;">三河</a></li>
            <li class="click"><a href="javascript:;">汕尾</a></li>
            <li class="click"><a href="javascript:;">四平</a></li>
            <li class="click"><a href="javascript:;">三门峡</a></li>
            <li class="click"><a href="javascript:;">松原</a></li>
            <li class="click"><a href="javascript:;">舒兰</a></li>
            <li class="click"><a href="javascript:;">双辽</a></li>
            <li class="click"><a href="javascript:;">遂宁</a></li>
            <li class="click"><a href="javascript:;">商洛</a></li>
            <li class="click"><a href="javascript:;">沙河</a></li>
            <li class="click"><a href="javascript:;">深州</a></li>
            <li class="click"><a href="javascript:;">宿州</a></li>
            <li class="click"><a href="javascript:;">沭阳县</a></li>
            <li class="click"><a href="javascript:;">射阳县</a></li>
            <li class="click"><a href="javascript:;">石嘴山</a></li>
            <li class="click"><a href="javascript:;">石龙</a></li>
            <li class="click"><a href="javascript:;">四会</a></li>
            <li class="click"><a href="javascript:;">上虞</a></li>
            <li class="click"><a href="javascript:;">嵊州</a></li>
            <li class="click"><a href="javascript:;">三水</a></li>
            <li class="click"><a href="javascript:;">天津</a></li>
            <li class="click"><a href="javascript:;">太原</a></li>
            <li class="click"><a href="javascript:;">台州</a></li>
            <li class="click"><a href="javascript:;">泰安</a></li>
            <li class="click"><a href="javascript:;">泰州</a></li>
            <li class="click"><a href="javascript:;">唐山</a></li>
            <li class="click"><a href="javascript:;">桐乡</a></li>
            <li class="click"><a href="javascript:;">吐鲁番</a></li>
            <li class="click"><a href="javascript:;">铜陵</a></li>
            <li class="click"><a href="javascript:;">桐庐</a></li>
            <li class="click"><a href="javascript:;">塘厦</a></li>
            <li class="click"><a href="javascript:;">滕州</a></li>
            <li class="click"><a href="javascript:;">铁岭</a></li>
            <li class="click"><a href="javascript:;">通化</a></li>
            <li class="click"><a href="javascript:;">天水</a></li>
            <li class="click"><a href="javascript:;">太仓</a></li>
            <li class="click"><a href="javascript:;">洮南</a></li>
            <li class="click"><a href="javascript:;">图们</a></li>
            <li class="click"><a href="javascript:;">铜川</a></li>
            <li class="click"><a href="javascript:;">桐城</a></li>
            <li class="click"><a href="javascript:;">天长</a></li>
            <li class="click"><a href="javascript:;">天门</a></li>
            <li class="click"><a href="javascript:;">泰兴</a></li>
            <li class="click"><a href="javascript:;">铜山县</a></li>
            <li class="click"><a href="javascript:;">通辽市</a></li>
            <li class="click"><a href="javascript:;">铜仁</a></li>
        </ul>
        <ul style="display: none">
            <li class="click"><a href="javascript:;">武汉</a></li>
            <li class="click"><a href="javascript:;">乌鲁木齐</a></li>
            <li class="click"><a href="javascript:;">温州</a></li>
            <li class="click"><a href="javascript:;">潍坊</a></li>
            <li class="click"><a href="javascript:;">威海</a></li>
            <li class="click"><a href="javascript:;">无锡</a></li>
            <li class="click"><a href="javascript:;">芜湖</a></li>
            <li class="click"><a href="javascript:;">武夷山</a></li>
            <li class="click"><a href="javascript:;">万州</a></li>
            <li class="click"><a href="javascript:;">吴江</a></li>
            <li class="click"><a href="javascript:;">万宁</a></li>
            <li class="click"><a href="javascript:;">五指山</a></li>
            <li class="click"><a href="javascript:;">文登</a></li>
            <li class="click"><a href="javascript:;">渭南</a></li>
            <li class="click"><a href="javascript:;">瓦房店</a></li>
            <li class="click"><a href="javascript:;">武安</a></li>
            <li class="click"><a href="javascript:;">武威</a></li>
            <li class="click"><a href="javascript:;">婺源</a></li>
            <li class="click"><a href="javascript:;">乌海</a></li>
            <li class="click"><a href="javascript:;">乌兰浩特</a></li>
            <li class="click"><a href="javascript:;">吴忠</a></li>
            <li class="click"><a href="javascript:;">文山</a></li>
            <li class="click"><a href="javascript:;">梧州</a></li>
            <li class="click"><a href="javascript:;">温岭</a></li>
            <li class="click"><a href="javascript:;">西安</a></li>
            <li class="click"><a href="javascript:;">西宁</a></li>
            <li class="click"><a href="javascript:;">徐州</a></li>
            <li class="click"><a href="javascript:;">襄阳</a></li>
            <li class="click"><a href="javascript:;">新乡</a></li>
            <li class="click"><a href="javascript:;">厦门</a></li>
            <li class="click"><a href="javascript:;">湘潭</a></li>
            <li class="click"><a href="javascript:;">咸阳</a></li>
            <li class="click"><a href="javascript:;">宣城</a></li>
            <li class="click"><a href="javascript:;">新余</a></li>
            <li class="click"><a href="javascript:;">孝感</a></li>
            <li class="click"><a href="javascript:;">咸宁</a></li>
            <li class="click"><a href="javascript:;">萧山</a></li>
            <li class="click"><a href="javascript:;">新民</a></li>
            <li class="click"><a href="javascript:;">荥阳</a></li>
            <li class="click"><a href="javascript:;">新郑</a></li>
            <li class="click"><a href="javascript:;">信阳</a></li>
            <li class="click"><a href="javascript:;">许昌</a></li>
            <li class="click"><a href="javascript:;">兴城</a></li>
            <li class="click"><a href="javascript:;">西昌</a></li>
            <li class="click"><a href="javascript:;">兴平</a></li>
            <li class="click"><a href="javascript:;">邢台</a></li>
            <li class="click"><a href="javascript:;">辛集</a></li>
            <li class="click"><a href="javascript:;">新乐</a></li>
            <li class="click"><a href="javascript:;">信丰</a></li>
            <li class="click"><a href="javascript:;">仙桃</a></li>
            <li class="click"><a href="javascript:;">湘乡</a></li>
            <li class="click"><a href="javascript:;">兴化</a></li>
            <li class="click"><a href="javascript:;">新泰</a></li>
            <li class="click"><a href="javascript:;">忻州</a></li>
            <li class="click"><a href="javascript:;">锡林浩特</a></li>
            <li class="click"><a href="javascript:;">香格里拉</a></li>
            <li class="click"><a href="javascript:;">新密</a></li>
            <li class="click"><a href="javascript:;">银川</a></li>
            <li class="click"><a href="javascript:;">岳阳</a></li>
            <li class="click"><a href="javascript:;">烟台</a></li>
            <li class="click"><a href="javascript:;">扬州</a></li>
            <li class="click"><a href="javascript:;">盐城</a></li>
            <li class="click"><a href="javascript:;">宜昌</a></li>
            <li class="click"><a href="javascript:;">益阳</a></li>
            <li class="click"><a href="javascript:;">义乌</a></li>
            <li class="click"><a href="javascript:;">运城</a></li>
            <li class="click"><a href="javascript:;">延吉</a></li>
            <li class="click"><a href="javascript:;">玉林</a></li>
            <li class="click"><a href="javascript:;">阳江</a></li>
            <li class="click"><a href="javascript:;">永康</a></li>
            <li class="click"><a href="javascript:;">玉溪</a></li>
            <li class="click"><a href="javascript:;">宜宾</a></li>
            <li class="click"><a href="javascript:;">兖州</a></li>
            <li class="click"><a href="javascript:;">延安</a></li>
            <li class="click"><a href="javascript:;">榆林</a></li>
            <li class="click"><a href="javascript:;">营口</a></li>
            <li class="click"><a href="javascript:;">宜兴</a></li>
            <li class="click"><a href="javascript:;">伊春</a></li>
            <li class="click"><a href="javascript:;">宜春</a></li>
            <li class="click"><a href="javascript:;">鹰潭</a></li>
            <li class="click"><a href="javascript:;">榆树</a></li>
            <li class="click"><a href="javascript:;">雅安</a></li>
            <li class="click"><a href="javascript:;">余杭</a></li>
            <li class="click"><a href="javascript:;">仪征</a></li>
            <li class="click"><a href="javascript:;">扬中</a></li>
            <li class="click"><a href="javascript:;">阳泉</a></li>
            <li class="click"><a href="javascript:;">禹州</a></li>
            <li class="click"><a href="javascript:;">义马</a></li>
            <li class="click"><a href="javascript:;">永城</a></li>
            <li class="click"><a href="javascript:;">云浮</a></li>
            <li class="click"><a href="javascript:;">余姚</a></li>
            <li class="click"><a href="javascript:;">盐田</a></li>
            <li class="click"><a href="javascript:;">株洲</a></li>
            <li class="click"><a href="javascript:;">淄博</a></li>
            <li class="click"><a href="javascript:;">郑州</a></li>
            <li class="click"><a href="javascript:;">珠海</a></li>
            <li class="click"><a href="javascript:;">中山</a></li>
            <li class="click"><a href="javascript:;">肇庆</a></li>
            <li class="click"><a href="javascript:;">漳州</a></li>
            <li class="click"><a href="javascript:;">张家港</a></li>
            <li class="click"><a href="javascript:;">涿州</a></li>
            <li class="click"><a href="javascript:;">湛江</a></li>
            <li class="click"><a href="javascript:;">镇江</a></li>
            <li class="click"><a href="javascript:;">诸暨</a></li>
            <li class="click"><a href="javascript:;">舟山</a></li>
            <li class="click"><a href="javascript:;">张家界</a></li>
            <li class="click"><a href="javascript:;">枣庄</a></li>
            <li class="click"><a href="javascript:;">遵化</a></li>
            <li class="click"><a href="javascript:;">遵义</a></li>
            <li class="click"><a href="javascript:;">增城</a></li>
            <li class="click"><a href="javascript:;">周口</a></li>
            <li class="click"><a href="javascript:;">驻马店</a></li>
            <li class="click"><a href="javascript:;">庄河</a></li>
            <li class="click"><a href="javascript:;">自贡</a></li>
            <li class="click"><a href="javascript:;">张家口</a></li>
            <li class="click"><a href="javascript:;">张掖</a></li>
            <li class="click"><a href="javascript:;">樟树</a></li>
            <li class="click"><a href="javascript:;">章丘</a></li>
            <li class="click"><a href="javascript:;">诸城</a></li>
            <li class="click"><a href="javascript:;">中卫</a></li>
            <li class="click"><a href="javascript:;">昭通</a></li>
            <li class="click"><a href="javascript:;">镇远</a></li>
        </ul>
    </div>
</div>
<script type="text/javascript">
$(document).ready(function(){
    $('#start_address').focus(function(){
        var width  = $(this).offset().left;
        var height = $(this).offset().top;
        var inputHeight = $(this).height();
        $('body').css('position', 'relative');
        $('#cityarea').css({
            'left': width,
            'top' : height + inputHeight - 28,
            'zIndex':9999
        }).show();
    });
    $('#start_address').blur(function(){
        //点击字母，切换城市
        $('#cityarea .search-citys-tt a').click(function(){
            var index = $(this).index();
            $(this).addClass('current').siblings().removeClass('current');
            $('#cityarea .search-citys-list ul').eq(index).show().siblings().hide();
        });
        //点击城市，选择城市
        $('#cityarea .search-citys-list a').click(function(){
            $('#start_address').val($(this).text());
            $('#cityarea').hide();
        });
        //关闭选择城市
        $('body, #cityarea .pop-close').click(function(e){
            var classname= $(e.target)[0].className;
            if (classname.indexOf('click') > '-1' || $(e.target)[0].id=='start_address') return;
            $('#cityarea').hide();
        });
    });
    
    $('#start_address').keyup(function(){
        $('#cityarea').hide();
    });
});
</script>